---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: eureka-services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eureka-services
  template:
    metadata:
      labels:
        app: eureka-services
    spec:
      containers:
      - name: eureka-services
        image: 090380/eureka-services-1:latest
        ports:
        - containerPort: 8761

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-balancer
  labels:
    app: eureka-services
spec:
  type: LoadBalancer
  ports:
  - port: 8761
    targetPort: 8761
    protocol: TCP
    nodePort: 31001
  selector:
    app: eureka-services