---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gateway-services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-services
  template:
    metadata:
      labels:
        app: gateway-services
    spec:
      containers:
      - name: gateway-services
        image: 090380/gateway-1:latest
        ports:
        - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-services-balancer
  labels:
    app: gateway-services
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
    nodePort: 51000
  selector:
    app: gateway-services